%% Generated by the Erlang ASN.1 compiler version:3.0
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition,in module SMP



-ifndef(_SMP_HRL_).
-define(_SMP_HRL_, true).

-record('Auth',{
username, token, services}).

-record('Person',{
name, surname, username, status}).

-record('Presence',{
size, userlist}).

-record('Add',{
user, status}).

-record('Confirm',{
user, type}).

-record('Room',{
name, id}).

-record('Create',{
room, description, acl, settings}).

-record('Join',{
room, answer}).

-record('RoomEvent',{
room, message, author}).

-record('Message',{
author, room, body, status}).

-endif. %% _SMP_HRL_
